CREATE TABLE IF NOT EXISTS `telegram_history` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `update_id` BIGINT UNSIGNED DEFAULT NULL COMMENT 'ID обновления от Telegram',
    `type` VARCHAR(50) NOT NULL COMMENT 'Тип события (message, callback_query, edited_message и т.д.)',
    `chat_id` BIGINT DEFAULT NULL COMMENT 'ID чата',
    `user_id` BIGINT DEFAULT NULL COMMENT 'ID пользователя',
    `username` VARCHAR(255) DEFAULT NULL COMMENT 'Username пользователя',
    `first_name` VARCHAR(255) DEFAULT NULL COMMENT 'Имя пользователя',
    `last_name` VARCHAR(255) DEFAULT NULL COMMENT 'Фамилия пользователя',
    `text` TEXT DEFAULT NULL COMMENT 'Текст сообщения',
    `callback_data` VARCHAR(255) DEFAULT NULL COMMENT 'Данные callback кнопки',
    `raw_data` TEXT DEFAULT NULL COMMENT 'Полные данные обновления в JSON',
    `direction` ENUM('incoming', 'outgoing') NOT NULL DEFAULT 'incoming' COMMENT 'Направление: входящее или исходящее',
    `status` VARCHAR(50) DEFAULT NULL COMMENT 'Статус (sent, delivered, read, error)',
    `error_message` TEXT DEFAULT NULL COMMENT 'Сообщение об ошибке, если есть',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `processed_at` TIMESTAMP NULL DEFAULT NULL COMMENT 'Время обработки',
    PRIMARY KEY (`id`),
    INDEX `idx_update_id` (`update_id`),
    INDEX `idx_chat_id` (`chat_id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_type` (`type`),
    INDEX `idx_direction` (`direction`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='История взаимодействий с Telegram ботом';
